MODULE numeric_kinds
  INTEGER, PARAMETER  :: dp = KIND(1D0)
  INTEGER, PARAMETER  :: np = KIND(1.0)
  INTEGER, PARAMETER  :: dc = KIND((1D0,1D0))
  INTEGER, PARAMETER  :: nc = KIND((1.,1.))
  INTEGER, PARAMETER  :: lg = KIND(.TRUE.)
  INTEGER, PARAMETER  :: ch = KIND("a")
  INTEGER, PARAMETER  :: di = SELECTED_INT_KIND(9)
  INTEGER, PARAMETER  :: ni = SELECTED_INT_KIND(3)
  INTEGER, PARAMETER  :: li = SELECTED_INT_KIND(1)
END MODULE numeric_kinds
